services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api_server:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api_server
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "8000:8000"
    networks:
      - app-network

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    container_name: pubsub_subscriber
    depends_on:
      - api_server
#    environment:
#      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
#      - GCP_SUBSCRIPTION_ID=${GCP_SUBSCRIPTION_ID}
#      - API_URL=${API_URL}
#      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - app-network

  publisher:
    build:
      context: .
      dockerfile: Dockerfile.publisher
    container_name: pubsub_publisher
    depends_on:
      - api_server
#    environment:
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
